from node import Node

RX = Node('RX', None,[
    Node('RXbridged-bidentate',None,[
        Node('CXRCX',None,[
            Node('C=X=R-C-XR2',None,None),
            Node('R2C-X-R-C-XR2',None,None),
            Node('RC=X-R=C-XR',None,None),
            Node('RC-X=R-C-XR2',None,None),
            Node('RC=X-R-C-XR2',None,None),
            Node('RC-X=R=C-XR',None,None),
            Node('RC-X=R=C=X',None,None),
            Node('C#X-R-C-XR2',None,None),
            Node('C#X-R=C-XR',None,None),
            Node('C#X-R-C#X',None,None),
            Node('RC=X-R-C=XR',None,None),
            Node('C#X-R-C=XR',None,None),
            ]),
        Node('CXROX',None,
             Node('RC-X=R-O-X',None,None),
             ),
        Node('O*RO*',None,
             Node('O-X-C-O-X',None,None),
             ),
        ]),
    Node('RXbidentate',None,[
        Node('CXCX',None,[
            Node('C-XC-X',None,None),
            Node('C=XRC=XR',None,None),
            Node('C-XR2C-XR2',None,None),
            Node('C-XR2C=XR',None,None),
            Node('C-XRC=X',None,None),
            Node('C=XRC-XR',None,None),
            Node('C#XC-XR',None,None),
            Node('C#XC-XR2',None,None),
            Node('C#XC=XR',None,None),
            Node('C-XR2C-XR',None,None),
            Node('C-XRC-XR',None,None),
            ]),
        Node('NXCX',None,[
            Node('inv(C=XRN=X)',None,None),
            Node('inv(C-XR2N=X)',None,None),
            Node('inv(C-XR2N-XR)',None,None),
            Node('inv(C=XRN-XR)',None,None),
            Node('inv(C-XRN-X)',None,None),
            Node('inv(C-XRN=X)',None,None),
            Node('inv(C-XRN-XR)',None,None),
            ]),
        Node('CXNX',None,[
            Node('C=XRN=X',None,None),
            Node('C-XR2N=X',None,None),
            Node('C-XR2N-XR',None,None),
            Node('C=XRN-XR',None,None),
            Node('C-XRN-X',None,None),
            Node('C-XRN=X',None,None),
            Node('C-XRN-XR',None,None),
            ]),
        Node('CXOX',None,[
            Node('C=XRO-X',None,None),
            Node('C-XR2O-X',None,None),
            Node('C-XRO-X',None,None),
            ]),
        Node('NXNX',None,[
            Node('N-XRN-XR',None,None),
            Node('N-XRN=X',None,None),
            ]),
        Node('NXOX',None,[
            Node('N-XRO-X',None,None),
            Node('N[+]=XR[-]O-X',None,None),
            ]),
        Node('OXOX',None,None),
        ]),
    Node('RXsingle-chemisorbed',None,[
        Node('CX',None,[
            Node('CqX',None,None),
            Node('C#XR',None,[
                Node('C#XCR3',None,None),
                Node('C#XN',None,None),
                Node('C#XOR',None,None),
                Node('C#XCR2',None,None),
                ]),
            Node('C=XR2',None,[
                Node('C=XRCR3',None,None),
                Node('C=XROR',None,None),
                Node('C=XRN',None,None),
                Node('C=XRCR2',None,None),
                ]),
            Node('C=X(=R)',None,[
                Node('C=X(=C)',None,None),
                Node('C=X(=NR)',None,None),
                ]),
            Node('C-XR3',None,[
                Node('C-XR2CR3',None,None),
                Node('C-XR2N',None,None),
                Node('C-XR2OR',None,None),
                ]),
            Node('C-XR2',None,[
                Node('C-XRO',None,None),
                Node('C-XRCR2',None,None),
                Node('C-XRNR',None,None),
                Node('C-XRN',None,None),
                ]),
            ]),
        Node('NX',None,[
            Node('N#X',None,None),
            Node('N=XR',None,[
                Node('N=XC-R',None,None),
                Node('N=XN',None,None),
                Node('N=XOR',None,None),
                Node('N=XC#R',None,None),
                ]),
            Node('N-XR2',None,[
                Node('N-XRCR3',None,None),
                Node('N-XRNR2',None,None),
                Node('N-XROR', None,None),
                Node('N-XRNR',None,None),
                Node('N-XRCR',None,None),
                Node('N[+]-XR[-]R',None,None),
                Node('N[+]=XR[-]R',None,None),
                ]),
            Node('N-XR',None,[
                Node('N-XCR2',None,None),
                Node('N-XNR',None,None),
                Node('N-XCR',None,None),
                ]),
            ]),
        Node('OX',None,[
            Node('O=X',None,None),
            Node('O-XR',None,[
                Node('O-XCR3',None,None),
                Node('O-XCR2',None,None),
                Node('O-XN',None,None),
                Node('O-XOR',None,None),
                ]),
            ]),
        ]),
    Node('RXvdw',None,[
        Node('(CR4)X',None,[
            Node('(CR3CR3)X',None,None),
            Node('(CR3N)X',None,None),
            Node('(CR3OR)X',None,None),
            ]),
        Node('(CR3)X',None,[
            Node('(CR2N)X',None,None),
            Node('(CR2CR)X',None,None),
            Node('(CR2O)X',None,None),
            ]),
        Node('(CR2)X',None,[
            Node('(CRN)X',None,None),
            Node('(CRCR)X',None,None),
            ]),
        Node('(NR3)X',None,[
            Node('(NN)X',None,None),
            Node('(NO)X',None,None),
            Node('(NC)X',None,None),
            ]),
        Node('(NR2)X',None,
             Node('(N=C)X',None,None),
             ),
        Node('(OR2)X',None,
             Node('(OROR)X',None,None),
             ),
        Node('(OR)X',None,
             Node('(ONR)X',None,[
                 Node('(ONOR)X',None,None),
                 Node('(ONN)X',None,None),
                 ]),
             ),
        ]),
    ])


print(len(RX.get_all_children()))
